version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: linkedu_postgres
    environment:
      POSTGRES_DB: linkedu_db
      POSTGRES_USER: linkedu_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend  
    container_name: linkedu_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/linkedu_db
      SPRING_DATASOURCE_USERNAME: linkedu_user
      SPRING_DATASOURCE_PASSWORD: your_password
      FRONTEND_URL: http://localhost:4200

      # 🔧 EMAIL (temporary test value)
      EMAIL_APP_PASSWORD: "iizn ngrk cgzd buhg"

      # 🔧 GROQ APIs (temporary test values)
      GROQ_API_KEY: "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"
      GROQ_CHATBOT_API_KEY: "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"

    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build: ./frontend
    container_name: linkedu_frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  postgres_data:
  uploads_data: